name: Print Software Versions
on:
 push:
   branches: main
jobs:
     PrintlanguageVersions:
                          runs-on: ubuntu-latest
                          steps:
                            - name: java version
                              run: java --version
                            - name: print tomcat version
                              run: tomcat --version
     Printdbms:
                        runs-on: ubuntu-latest
                        needs: [PrintlanguageVersions]
                        steps:
                        - name: mysql version
                          run: mysql -V
   
