name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintlanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Показати версію Java
        run: java --version

      - name: Встановити Apache Tomcat
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.58/bin/apache-tomcat-9.0.58.tar.gz
          tar -xzf apache-tomcat-9.0.58.tar.gz
          sudo mv apache-tomcat-9.0.58 /opt/tomcat

      - name: Показати версію Apache Tomcat
        run: /opt/tomcat/bin/version.sh

  Printdbms:
    runs-on: ubuntu-latest
    needs: [PrintlanguageVersions]
    steps:
      - name: Показати версію MySQL
        run: mysql -V
